### ISSUE TITLE
Use @documentlanguage to search engine optimization

### ISSUE THREAD

**Issue by takueof** [ayatakesi/emacs-doc-ja#1]
`@documentlanguage` の設定がない（GitHub 上の検索ではヒットしなかった）ため、デフォルトの `en` が使われているようです。
前述の状況により `<body lang="en">` になってしまい、検索エンジンに日本語のドキュメントとして認識されづらくなっている可能性があります。
可能であれば、どこかで `@documentlanguage ja` を全体指定していただきたいのですが、そもそも可能なのでしょうか……？

See also:

* https://www.gnu.org/software/texinfo/manual/texinfo/html_node/_0040documentlanguage.html

**Comment by ayatakesi** [comment]
japanese_texis/Makefile.example内のmakeinfo、texi2* の呼び出しオプションで--document-language=STRと回避はできそうですが、japanese_texis配下の*.texiのドキュメント言語が日本語なので、ファイル中で指定したいところですねえ。ちょっと調べてみます。
ありがとうございます。

**Comment by ayatakesi** [comment]
遅くなってしまい申し訳ありません。

ちょっと調べたり試してみたんですが、、、

ファイル中で指定したいと言った件については、指定するべきオリジナルのファイル(docstyle.texi)に@documentlanguage指定がないため、翻訳ツール(po4aやgettext)による対応ではなく、別途指定行を挿入する必要がある(特段難しい処理ではありませんが)。

texinfo文書の本格的な日本語化には、https://www.trueroad.jp/2016/05/14-01.html で説明されているようにtexinfo-ja.texやtxi-ja.texの追加(GNU texinfoに同梱されているので上流を追うのがちょっとだけ煩雑になる)、\inputというpo4aでハンドリングされない(emacs.texi.poやelisp.texi.poにメッセージとして抽出されない)行を置き換える必要がある(これまた難しい処理ではありませんが)。

本格的な日本語化のテストや影響確認がわたしの手に余る(すいません)。

…等の理由により、Makefile.example中のmakeinfoやtexi2*のコマンドオプションで--document-language=jaを指定して逃げようと思います(とりあえずこれで他に影響なく、body lang="ja"になりました)。

**Comment by ayatakesi** [comment]
5e59f6afcc76a75b01be3443069017d1044bf532 で対応しました
