### ISSUE TITLE
elisp 35.3.3.1 rx 翻訳ミスと思われる記述

### ISSUE THREAD

**Issue by BrownShibaDog** [ayatakesi/emacs-doc-ja#3]
いつも和訳マニュアルに大変お世話になっております。ありがとうございます。

elisp infoマニュアルを読んでいて、たまたま誤訳と思われる箇所を見つけました。
確認をお願いします。

https://github.com/ayatakesi/emacs-doc-ja/blob/19551946264d6b29377aecaa565744f90b49a8ba/lispref/searching.texi.po#L2163-L2164

`0回以上マッチする` かと思います。

**Comment by ayatakesi** [comment]
誤訳です。
ありがとうございます。
修正しますー

**Comment by BrownShibaDog** [comment]
ありがとうございます！

**Comment by ayatakesi** [comment]
対応終わりましたのでクローズします。ご報告ありがとうございました😀
