### ISSUE TITLE
property / properties の訳

### ISSUE THREAD

**Issue by m-kirihara** [ayatakesi/emacs-doc-ja#7]
property / properties に対して「プロパティ」と「プロパティー」の両方の訳が見受けられ，どちらかに統一した方がいいと思うのですが……，どうでしょうか？

(何でしたら，どちらかに統一した Pull request を作りますが．(と言うより，sed (や perl) で置換するだけですが．) 私の好みは Windows で使われている「プロパティ」です．)

**Comment by ayatakesi** [comment]
そうですね、統一したいです(主にスマホで作業してるんですが、その時々でお薦めの順位が違う場合があるのです)。pullリクはemacs-doc-jaレポジトリのemacs-29ブランチにあるlispref/*.poにお願いします。後、一括置換の場合は一括置換後の修整前後確認も必要です。

**Comment by ayatakesi** [comment]
プロパティに統一したいと思います。
